services:
  otternel:
    build: .
    container_name: service-otternel
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVERLOG_FOLDER=/serverlog
    volumes:
      # TODO : REPLACE WITH A PROXY TO AVOID GIVING DOCKER ACCESS TO THE HOST FILE SYSTEM ASAP
      - /var/run/docker.sock:/var/run/docker.sock
      # Read only server logs
      - /opt/docker/minecraft/la_vanilla_s4/data/logs:/serverlog/1:ro
      - /opt/docker/palworld/palworld_vanilla/data/Pal/Saved/Logs:/serverlog/3:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mysql_network

networks:
  mysql_network:
    external: true
    name: mysql_network