[[trigger]]
name = "doing_tests" # Name of the trigger
game = "minecraft" # Game concerned by the trigger (Not set = All and any game)
pattern = "Th1s 1s 4 7e57" # Regex partern triggering the action function
serverlog_ids = [1] # Server ids concerned by the trigger (Not set = All and any server)
function = "on_test" # Function called in the action crate

[[trigger]]
name = "minecraft_player_joined"
game = "minecraft"
pattern = ".* .* .* joined the game"
serverlog_ids = [1, 2]
function = "on_player_joined"

[[trigger]]
name = "minecraft_player_left"
game = "minecraft"
pattern = ".* .* .* left the game"
serverlog_ids = [1, 2]
function = "on_player_left"

[[trigger]]
name = "minecraft_player_advancement"
game = "minecraft"
pattern = ".* .* .* has made the advancement .*"
serverlog_ids = [1, 2]
function = "on_minecraft_player_advancement"

[[trigger]]
name = "minecraft_player_message"
game = "minecraft"
pattern = "^\\[.*\\]: <.*> .*"
serverlog_ids = [1, 2]
function = "on_player_message"